name: mynthone
description: Super app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  card_swiper: ^3.0.1
  connectivity_plus: ^3.0.3
  coupon_uikit: ^0.2.1
  device_preview: ^1.1.0
  fl_country_code_picker: ^0.1.9+1
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^9.2.0
  flutter_inner_drawer:
    git:
      url: https://github.com/kenjishiromajp/flutter_inner_drawer
      ref: kenjishiromajp-update-for-2.12-null-safety-casting
  flutter_otp_text_field: ^1.1.1
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  http: ^1.2.0
  intl: ^0.18.1
  local_auth: ^2.1.8
  logger: ^2.0.2+1
  lottie: ^3.1.0
  modal_bottom_sheet: ^2.1.2
  package_info_plus: ^5.0.1
  responsive_framework: ^1.1.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  supabase_flutter: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - .env.development
    - .env.staging
    - .env.production
    - assets/images/
    - assets/svg/
    - assets/json/
